@echo off
REM ================================================================================
REM Upload Checkpoint to RunPod Network Volume via SCP
REM 
REM This script uploads a checkpoint file to your RunPod Network Volume using SCP.
REM It uses the SSH key generated by runpodctl for authentication.
REM
REM Prerequisites:
REM   1. runpodctl configured (runpodctl config --apiKey YOUR_API_KEY)
REM   2. An active RunPod pod with SSH over TCP enabled
REM   3. Network Volume mounted at /workspace
REM
REM Usage:
REM   1. Edit the variables below with your pod's SSH info
REM   2. Run: upload_checkpoint.bat <checkpoint_filename>
REM   
REM Example:
REM   upload_checkpoint.bat checkpoint_step_172000.pt
REM ================================================================================

REM ============================================================================
REM CONFIGURATION - UPDATE THESE VALUES FOR YOUR POD
REM ============================================================================

REM RunPod SSH connection details (get from RunPod UI -> Your Pod -> Connect -> SSH over exposed TCP)
set POD_IP=194.68.245.189
set POD_PORT=22151

REM Local paths
set LOCAL_CHECKPOINTS_DIR=E:\GPT_SANDBOX_STORAGE\Experiment 2 - ChatML + Optimizations\checkpoints
set SSH_KEY=%USERPROFILE%\.runpod\ssh\RunPod-Key-Go

REM Remote path on RunPod Network Volume
set REMOTE_PATH=/workspace/Experiment 2 - ChatML + Optimizations/checkpoints/

REM ============================================================================
REM SCRIPT LOGIC - DO NOT EDIT BELOW THIS LINE
REM ============================================================================

echo.
echo ================================================================================
echo RunPod Checkpoint Upload Script
echo ================================================================================
echo.

REM Check if checkpoint filename was provided
if "%~1"=="" (
    echo ERROR: No checkpoint filename provided
    echo.
    echo Usage: upload_checkpoint.bat ^<checkpoint_filename^>
    echo Example: upload_checkpoint.bat checkpoint_step_172000.pt
    echo.
    echo Available checkpoints:
    dir /b "%LOCAL_CHECKPOINTS_DIR%\checkpoint_step_*.pt" 2>nul
    exit /b 1
)

set CHECKPOINT_FILE=%~1
set LOCAL_FILE=%LOCAL_CHECKPOINTS_DIR%\%CHECKPOINT_FILE%

REM Verify local file exists
if not exist "%LOCAL_FILE%" (
    echo ERROR: Checkpoint file not found: %LOCAL_FILE%
    echo.
    echo Available checkpoints:
    dir /b "%LOCAL_CHECKPOINTS_DIR%\checkpoint_step_*.pt" 2>nul
    exit /b 1
)

REM Verify SSH key exists
if not exist "%SSH_KEY%" (
    echo ERROR: SSH key not found: %SSH_KEY%
    echo.
    echo Please run: runpodctl config --apiKey YOUR_API_KEY
    echo This will generate the SSH key automatically.
    exit /b 1
)

REM Display upload info
echo Local file:  %LOCAL_FILE%
for %%A in ("%LOCAL_FILE%") do echo File size:   %%~zA bytes
echo.
echo Remote destination:
echo   Host: %POD_IP%
echo   Port: %POD_PORT%
echo   Path: %REMOTE_PATH%
echo.
echo SSH Key: %SSH_KEY%
echo.

REM Confirm upload
set /p CONFIRM="Continue with upload? (y/N): "
if /i not "%CONFIRM%"=="y" (
    echo Upload cancelled.
    exit /b 0
)

echo.
echo ================================================================================
echo Starting upload...
echo ================================================================================
echo.

REM Execute SCP upload
scp -P %POD_PORT% -o StrictHostKeyChecking=no -i "%SSH_KEY%" "%LOCAL_FILE%" root@%POD_IP%:"%REMOTE_PATH%"

if %ERRORLEVEL% EQU 0 (
    echo.
    echo ================================================================================
    echo Upload completed successfully!
    echo ================================================================================
    echo.
    echo Verify in your RunPod pod:
    echo   ls -lh "%REMOTE_PATH%"
    echo.
) else (
    echo.
    echo ================================================================================
    echo Upload failed with error code: %ERRORLEVEL%
    echo ================================================================================
    echo.
    echo Troubleshooting:
    echo   1. Verify pod is running and SSH is enabled
    echo   2. Check POD_IP and POD_PORT are correct
    echo   3. Ensure SSH key exists: %SSH_KEY%
    echo   4. Try connecting manually: ssh root@%POD_IP% -p %POD_PORT% -i "%SSH_KEY%"
    echo.
    exit /b %ERRORLEVEL%
)

exit /b 0
